version: "3.8"

services:
  backend:
    build: ./ai-ticket-assistant
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
      - MAILTRAP_SMTP_HOST=${MAILTRAP_SMTP_HOST}
      - MAILTRAP_SMTP_PORT=${MAILTRAP_SMTP_PORT}
      - MAILTRAP_SMTP_USER=${MAILTRAP_SMTP_USER}
      - MAILTRAP_SMTP_PASS=${MAILTRAP_SMTP_PASS}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - APP_URL=${APP_URL}
    depends_on: []
  
  frontend:
    build: ./ai-ticket-frontend
    ports:
      - "5173:80"
    environment:
      - VITE_SERVER_URL=http://localhost:3000/api
    depends_on:
      - backend